-- Calvary Control Room schema
-- Run this in Supabase SQL editor (project: pfycvgbrsbecznkcikwt) once.
-- All tables use RLS-off for v1 (anon key has full access). We'll tighten later.

-- ============================================================
-- 1. LIVE STATE  — the single row the overlay listens to
-- ============================================================
-- Exactly one row, id=1. Operator updates this, overlay subscribes.
-- payload is jsonb so we can change the shape without migrations.

create table if not exists control_room_live (
  id integer primary key default 1,
  mode text not null default 'blank',         -- blank | lyric | verse | graphic
  payload jsonb not null default '{}',        -- see shape below
  updated_at timestamptz not null default now(),
  updated_by text,                             -- operator name
  constraint only_one_row check (id = 1)
);

insert into control_room_live (id, mode, payload)
values (1, 'blank', '{}')
on conflict (id) do nothing;

-- Payload shapes:
--   mode = 'blank'   → payload = {}
--   mode = 'lyric'   → payload = { "song_title": "...", "line1": "...", "line2": "..." }
--   mode = 'verse'   → payload = { "reference": "John 3:16", "text": "For God so loved...", "version": "KJV" }
--   mode = 'graphic' → payload = { "name": "Welcome slide", "image_url": "https://..." }

-- ============================================================
-- 2. SERVICE PLANS  — the pre-loaded running order for a date
-- ============================================================

create table if not exists control_room_plans (
  id uuid primary key default gen_random_uuid(),
  service_date date not null,
  created_at timestamptz not null default now(),
  notes text,
  unique (service_date)
);

-- Items in the plan — songs, with their lyrics pre-split into slide pairs.
-- Order is controlled by `position`.
create table if not exists control_room_plan_items (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references control_room_plans(id) on delete cascade,
  position integer not null,
  kind text not null,                          -- song | graphic | note
  title text not null,                         -- e.g. "Days of Elijah"
  slides jsonb not null default '[]',          -- array of { line1, line2 } for kind=song
  graphic_url text,                            -- for kind=graphic
  section text,                                -- praise | worship | offering | end | other
  created_at timestamptz not null default now()
);

create index if not exists idx_plan_items_plan on control_room_plan_items(plan_id, position);

-- ============================================================
-- 3. BIBLE  — full text, one row per verse, for live search
-- ============================================================

create table if not exists control_room_bible (
  id serial primary key,
  version text not null,                       -- KJV, NIV, NLT etc.
  book text not null,                          -- "John", "1 Corinthians"
  book_num integer not null,                   -- 1..66
  chapter integer not null,
  verse integer not null,
  text text not null,
  unique (version, book, chapter, verse)
);

create index if not exists idx_bible_lookup on control_room_bible(version, book_num, chapter, verse);
create index if not exists idx_bible_book_chapter on control_room_bible(book, chapter);

-- ============================================================
-- 4. OPERATOR USERS  — PIN-gated access, same pattern as The Bridge
-- ============================================================

create table if not exists control_room_users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  pin_hash text not null,                      -- client-hashed, not a real password hash
  role text not null default 'operator',       -- operator | admin
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Seed Bolaji (PIN 2610) and Scott (PIN 1234 — he should change it)
-- Hashes generated by the same djb2 function used client-side:
--   bolaji 2610 → bp_yhwbc0   (Bolaji already uses this hash in The Bridge)
--   scott  1234 → bp_4bgyzg   (placeholder, Scott should update)
insert into control_room_users (name, pin_hash, role) values
  ('Bolaji Olatoye', 'bp_yhwbc0', 'admin'),
  ('Scott Shokoya',  'bp_4bgyzg', 'operator')
on conflict do nothing;

-- ============================================================
-- 5. REALTIME  — enable postgres_changes on live state
-- ============================================================
-- The overlay subscribes to this table. No publication setup needed on
-- Supabase; it's on by default for new tables. If realtime isn't firing:
--   Supabase dashboard → Database → Replication → enable for control_room_live.

-- Disable RLS for v1 (everything goes through the anon key)
alter table control_room_live         disable row level security;
alter table control_room_plans        disable row level security;
alter table control_room_plan_items   disable row level security;
alter table control_room_bible        disable row level security;
alter table control_room_users        disable row level security;
